### ISSUE TITLE
APIs examples do not load in docs.raml.org

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-docs#1]
Going to http://docs.raml.org/apis/amazon-s3/ shows an infinite loading Github image and this error: `Uncaught TypeError: content.forEach is not a function`

<img width="1439" alt="screen shot 2015-11-04 at 1 30 49 pm" src="https://cloud.githubusercontent.com/assets/1169708/10944524/616c9dc8-82f8-11e5-8fe6-548eb634b1de.png">

**Comment by petrochenko-pavel-a** [comment]
Pretty strange, it seems that content for this API was not prepared properly

**Comment by petrochenko-pavel-a** [comment]
we will investigate asap. Thanks for posting it, 

Regards,
Pavel

**Comment by dreamflyer** [comment]
can not to reproduce, reference works fine for me

**Comment by juancoen** [comment]
I cannot reproduce this anymore, thanks
